### PR TITLE
Handle strange spacing around css properties

### LINKED ISSUE #325: `css` and `style` attribute bindings don't handle strange whitespace
When you have something like

```html
<h1 css.bind="     color: ${selectedColor};">Hey</h1>
```

instead of

```html
<h1 css.bind="color: ${selectedColor};">Hey</h1>
```

Aurelia will ignore the style.

### PR DESCRIPTION
**Pull request by 32graham**
Resolves #325

### CODE REVIEW

**Comment by jdanyow** [comment]
@32graham thanks for the PR!

Could you please amend the commit message according to the guidelines in the contributing.md (our release notes are automated based on a specific commit message format).

@EisenbergEffect CLA check

**Comment by EisenbergEffect** [comment]
@jdanyow  CLA for @32graham is Confirmed

**Comment by 32graham** [comment]
@jdanyow I think I have the commit message correct now. Let me know if anything else needs fixed :smiley:

**Comment by jdanyow** [comment]
thanks @32graham!

**Pull request merged**
