### PR TITLE
fix(doc): Fix wrong URL in README.md

### PR DESCRIPTION
**Pull request by tricknotes**

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Would you mind signing our CLA? https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1

**Comment by tricknotes** [comment]
Thanks for reply @EisenbergEffect .
Now signed :pencil2:

**Comment by EisenbergEffect** [comment]
Apologies for taking so long to respond to the PR. Getting it merged in now :)

**Comment by tricknotes** [comment]
Thanks @EisenbergEffect :dancers: 
I missed to see [`CONTRIBUTING.md`](https://github.com/aurelia/binding/blob/master/CONTRIBUTING.md) :bow:

**Comment by EisenbergEffect** [comment]
It's not uncommon. No worries. Hope to see you around contributing more in the future. Everything is a help.

**Pull request merged**
