### PR TITLE
fix(ClassObserver): split classes by any ASCII whitespace. fixes #257

### LINKED ISSUE #257: class-observer throws DOMException on line break + tertiary operator
Line breaks in the class attribute throws a DOMException when combined with using the tertiary operator

Start with a working example:
```
<div class="${someBoolean ? 'is-true' : 'is-false'}">

</div>
```

Now insert a line break at the end (valid html according to https://validator.w3.org):
```
<div class="${someBoolean ? 'is-true' : 'is-false'}
">

</div>
```

The following exception is then thrown:
```
Unhandled promise rejection DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('is-true
') contains HTML space characters, which are not valid in tokens.
    at Error (native)
    at ClassObserver.setValue (http://localhost:9000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.0.2/aurelia-binding.js:3764:34)
```

The funny part is that the line break is part of the class name here https://github.com/aurelia/binding/blob/master/src/class-observer.js#L26

### PR DESCRIPTION
**Pull request by Gheoan**

### CODE REVIEW

**Comment by jdanyow** [comment]
@Gheoan thanks! Can you make the corresponding changes to the `ClassObserver` tests- as well as add a test for the new-line scenario?
https://github.com/aurelia/binding/blob/master/test/class-observer.spec.js

Please sign the CLA if you haven't done so already.

**Comment by Gheoan** [comment]
@jdanyow I made the first test to check for every possible ASCII whitespace. Are you ok with modifying the test or you want a new one?

**Comment by jdanyow** [comment]
thanks @Gheoan will review and merge asap- did you [sign the CLA](http://goo.gl/forms/dI8QDDSyKR)? (required for legal reasons)

**Comment by Gheoan** [comment]
@jdanyow I already signed the CLA

**Comment by EisenbergEffect** [comment]
@jdanyow Should we merge and add this to the forthcoming release?

**Comment by EisenbergEffect** [comment]
CLA confirmed.

**Comment by jdanyow** [comment]
Not yet- I need to fix the tests.  We can put it in the next release.

**Pull request merged**
