### PR TITLE
Added missing ;

### PR DESCRIPTION
**Pull request by yangchenyun**

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Would you mind signing our CLA? https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1  I will need that in order to accept your PR. Much thanks in advance!

**Comment by EisenbergEffect** [comment]
Thanks! Good catch :smile:

**Comment by yangchenyun** [comment]
This is the first I detect while reading through the code, looks there is bunch of them; probably could update some editor configuration to detect them :)

**Comment by EisenbergEffect** [comment]
Yes there are probably some other oversights. Thanks! We'll try to get some better checking in place.

**Pull request closed without merging**
