### PR TITLE
perf(binding): reduce target property overhead

### PR DESCRIPTION
**Pull request by jdanyow**
**Memory**
memory

**CPU**
cpu

### CODE REVIEW

**Comment by jdanyow** [comment]
with deferred-connect:
deferred

**Comment by EisenbergEffect** [comment]
Looks pretty significant. Why is the top total larger though?

**Comment by jdanyow** [comment]
The time labeled `(idle)` will be higher if I took longer to click stop on the cpu trace.  Safe to ignore that line.  

It doesn't seem to be possible to compare the actual times *across the three runs*... due to environmental factors perhaps?  Take `cloneNode` or `insertBefore` for example, they report a different "self" time in each of the 3 runs, even though they're doing the same thing each time (same template, same number of children, etc).  I was looking at the change in cost for each function in relation to other functions *in the same test run*- eg `createObserversLookup` falls to the bottom and `cloneNode` climbs to the top.  

Also implied in the "deferred connect" change is the memory increase related to setting up observers is deferred until after the rendering is done and is a more gradual climb due to the throttling in our `ConnectQueue`.

**Comment by EisenbergEffect** [comment]
Understood. So, is this all ready now, assuming we merge all PRs across the repos?

**Comment by adriatic** [comment]
You are almost dealing with the effects of Heisenberg's uncertainty principles here - given the size of scheduler's time-slice

**Comment by jdanyow** [comment]
@EisenbergEffect this is ready

**Pull request merged**
