### PR TITLE
fix(StyleObserver): parse complex styles

### PR DESCRIPTION
**Pull request by z-brooks**
Fix for https://github.com/aurelia/templating-resources/issues/248

Should parse anything with function(s), strings or plain values:
_example patterns_
```
abc-xyz: value;  abc: "value"; abc: 'value';
abc: func("..."); abc: func('...'); abc: func(...);
abc: func(test), func("test") func('...') "s:t\"ri;ng: ";
abc: e-f(g(...), xyz); 
background: url(data:image/gif;base64,X//YZ...);
```

### CODE REVIEW

**Comment by jdanyow** [comment]
now that's what I call a regex :)

**Comment by Gheoan** [comment]
I guess [*a regex*](https://github.com/aurelia/binding/issues/301#issuecomment-178907182) is enough.

**Comment by stsje** [comment]
It will be very difficult to maintain such a long and complex regex.
Would it be possible to have an implementation with less use of regex?

Maybe cssText can be used. A challenge is then removing old unused styles, we have no way of getting those.
https://jsfiddle.net/965qtx73/2/
```
var newValue = 'width: 50px; height: 40px; background-image: url("http://aurelia.io/test2.png"); background-color: blue;';

console.time("Style update");

var element = document.getElementById('element');
var tmpStyleElement = document.createElement('div');

tmpStyleElement.setAttribute('style', element.style.cssText + newValue);
element.setAttribute('style', tmpStyleElement.style.cssText);

console.timeEnd("Style update");
```
Pros are that it's quite simple and performant. Though the implementation is lacking removal of styles.

**Comment by stsje** [comment]
You sure we can't find a more maintainable solution?

**Comment by jdanyow** [comment]
@stsje PRs welcome!

I liked the old way, where we set `style.cssText` but this caused problems when integrating with other libraries that were also changing the element's styles, so we need to make sure the binding doesn't stomp on styles it doesn't "own".

**Comment by stsje** [comment]
@jdanyow What if we changed the way Aurelia supports style & class interpolation?
I don't see a way we can fix all the issues that might come with using a regex, and we certainly don't want to implement a css parser.
Issues like the one I just opened will probably keep popping up from time to time https://github.com/aurelia/templating-resources/issues/251

Currently I don't see a way we can use the native objects such as CSSRuleList to build a solid solution with the current interpolation.

**Pull request merged**
