### PR TITLE
feat(Array): observe array prototype methods

### PR DESCRIPTION
**Pull request by jdanyow**
@EisenbergEffect I'm working on tests now. Existing tests in binding and templating-resources are passing. Let me know what you think.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Was there any particular reason to store the original prototype methods on the Array prototype? As a results you have to have an extra deference via `this`. Could we just store them in module local variables instead?

**Comment by jdanyow** [comment]
hmm I don't know what I was thinking there. I've updated the pull request to capture the original prototype methods using local variables and added some tests to ensure the array mutation methods function properly whether the array is observed or not. Let me know if it looks good to merge.

**Comment by EisenbergEffect** [comment]
For perf reasons should the checks be more explicit?

```
if (this.__arrayObserver !== undefined) { ... }
```

**Comment by jdanyow** [comment]
Looks like we can squeeze a little bit of perf out:  http://jsperf.com/falsey-check-vs-explicit-check

Will update the PR

**Comment by jdanyow** [comment]
PR updated :zap:

**Comment by EisenbergEffect** [comment]
Looks good. How do you feel about it? If you're good, then please go ahead and do the merge :)

**Pull request merged**
