### PR TITLE
feat(computedFrom): support expressions

### LINKED ISSUE #149: computedFrom doesn't support paths
It is my understanding and my experience that `computedFrom` does not work with paths, like: `@computedFrom('user.firstName')`.

I think that this is a very hard limitation that should be lifted:
1. Modeling and using sub-properties is common once your application gets even moderately complex.
2. There is sometimes no good alternative to `computedFrom`.

My use case is a computed property that creates an array from complex computations and lookups from other arrays. Definitively not something you want to poll and it is too complex for the auto-observation plugin. On the other hand its dependency is trivial to express as it is a single, nested property.

### PR DESCRIPTION
**Pull request by jdanyow**
fixes #149

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Very interesting stuff. With this in place, what do you think about adding the auto-dependency checking stuff that you had in that other plugin? Is it easy to add on top of this now that it's there? Or is that completely different?

**Comment by jdanyow** [comment]
Definitely a step towards integrating that. If we do add the aurelia-computed capability here it would probably need to be opt-in via a decorator right? The explicit nature of the decorator would allow us to throw errors when we are not able to parse the expression(s) in the getter function's toString result.

The other thing related to this I'm investigating is support for https://github.com/aurelia/binding/issues/147 by adding logic to `@computedFrom` that would rewrite this:
```js
@computedFrom('some', 'stuff')
myClassMethod(myArg) {
  ...
}
```
to the equivalent of something like this:
```js
_myClassMethod(myArg) {
  ...
}

@computedFrom('some', 'stuff')
get myClassMethod() {
  return _myClassMethod.bind(this);
}
```

Then it should "just work":tm: provided [this line](https://github.com/aurelia/binding/blob/1.0.0-beta.1.2.2/src/ast.js#L284) is added [here](https://github.com/aurelia/binding/blob/1.0.0-beta.1.2.2/src/ast.js#L390).

What do you think?

**Comment by EisenbergEffect** [comment]
Sounds pretty good to me.

**Comment by EisenbergEffect** [comment]
Should we rename `computedFrom` to `computed` so that if you use it without an args it will auto-compute the props? (We can keep computedFrom and just create an alias to computed and deprecate the old one.)

**Comment by jdanyow** [comment]
`computed` sounds good to me.  Will create a PR for that and the `aurelia-computed` logic integration.

Update on https://github.com/aurelia/binding/issues/147: my plan didn't quite work.  The changes to the decorator:
```js
export function computedFrom(...rest) {
  return function(target, key, descriptor) {
+    if (!descriptor.get) {
+      let innerKey = '__' + key;
+      Object.defineProperty(target, innerKey, { enumerable: false, configurable: true, value: descriptor.value });
+      descriptor.get = function() { return this[innerKey]; };
+      descriptor.set = function(newValue) { this[innerKey] = newValue; };
+      delete descriptor.value;
+      delete descriptor.writable;
+    }
  
    descriptor.get.dependencies = rest;
    return descriptor;
  }
}
```

Basically say "when the dependencies change, notify the binding system that the decorated class method changed".  This doesn't work.  The class method doesn't ever change. The result of *invoking* the class method potentially has changed. [This check](https://github.com/aurelia/binding/blob/1.0.0-beta.1.2.2/src/binding-engine.js#L123) (which is a valid check) prevents the change event from bubbling up and causing the binding to reevaluate.

Will need to think about https://github.com/aurelia/binding/issues/147 a bit more while working on the rest of this stuff.

OK to merge what I have so far?

**Comment by jdanyow** [comment]
this was merged but rebasing the branch prevented the PR from closing automatically.  Closing this manually...

**Comment by sormy** [comment]
Does it work well? It looks like even previously working syntax without expressions stop to work well.

I got master, build it and use method like that:
```
  @computedFrom('offset', 'topOffset', 'hourHeight')
  get top() {
    console.log('event get top()')
    return this.topOffset + this.offset * this.hourHeight / 60;
  }
```

and the code fall back to dirty checking and eating all cpu.

**Pull request closed without merging**
