### PR TITLE
fix(event-manager) fix captured/delegated event decrement

### PR DESCRIPTION
**Pull request by gavinaiken**
fixes this issue: https://github.com/aurelia/binding/issues/747

### CODE REVIEW

**Comment by bigopon** [comment]
Nice 👍 , and that's quite an oopsie 😆 . Pinging @Alexander-Taran and @fkleuver 
This look good to me. Thanks!.

@gavinaiken Please remove changes related to dist files.

**Comment by fkleuver** [comment]
Thank you @gavinaiken, it looks good to me. Could you do one thing please and re-submit this PR based off the develop branch, and target it to the develop branch? That way the workflow will automatically pick everything up and we can release immediately after merging

**Comment by bigopon** [comment]
You can click edit button top right to retarget different branch

**Comment by gavinaiken** [comment]
Closing this in favour of https://github.com/aurelia/binding/pull/749

**Comment by fkleuver** [comment]
@bigopon I did that first as you can see in conversation history but that dragged some other changes from the diff between develop/master into this PR :)
thanks @gavinaiken !

**Pull request closed without merging**
