### PR TITLE
ES6 object initializer property name shorthand

### PR DESCRIPTION
**Pull request by z-brooks**
https://github.com/aurelia/templating-binding/issues/75

### CODE REVIEW

**Comment by jdanyow** [comment]
@EisenbergEffect CLA check

**Comment by EisenbergEffect** [comment]
The CLA is confirmed @jdanyow 
Thanks @z-brooks for the sweet contribution!

**Comment by EisenbergEffect** [comment]
@jdanyow Is this ok to merge?

**Comment by jdanyow** [comment]
@z-brooks thanks! :dancers:

**Pull request merged**
