### PR TITLE
feat(decorator-observable): add observable property decorator

### PR DESCRIPTION
**Pull request by Scapal**
Implement #270

### CODE REVIEW

**Comment by jdanyow** [comment]
:muscle: thanks @Scapal!  Can you confirm this works in the typescript skeleton? I did a quick test in the [typescript playground](http://www.typescriptlang.org/Playground) and it didn't look like it was working in TS.

@EisenbergEffect CLA check

**Comment by Scapal** [comment]
@jdanyow now it works in the typescript skeleton (and still works using Babel)

**Comment by jdanyow** [comment]
@Scapal thanks!

**Comment by glen-84** [comment]
Is there anything similar for observing changes to array elements?

**Pull request merged**
