### PR TITLE
fix(parser): left-to-right associativity for nested binary expression…

### PR DESCRIPTION
**Pull request by fkleuver**
Somehow I missed this one. Big oops. Fixes https://github.com/aurelia/binding/issues/586#issuecomment-399044403

@EisenbergEffect

### CODE REVIEW

**Comment by qraynaud** [comment]
Thanks @fkleuver. You are really quick!

**Comment by fkleuver** [comment]
Not quite there yet. I added some failing tests. I need to go for about a 2 hours and will fix this properly asap when im back.

**Comment by fkleuver** [comment]
Agreed. Binary parsing received the biggest rework and I only tested precedence, not associativity. My sincere apologies!

**Comment by qraynaud** [comment]
Thanks a lot. And really you don't need to apologize. I could have done the same. I'm just concerned about others that might be struggling right now to understand why their shiny component is broken :-). I've added parens on my side and everything is fine again.

**Pull request merged**
