### PR TITLE
feat(BindingEngine): option controlling AccessMember assign behavior

### LINKED ISSUE #205: Consider adding an option to control AccessMember's automatic object creation
`AccessMember` [automatically creates an object](https://github.com/aurelia/binding/blob/0.10.2/src/ast.js#L189) when assigning a value to a property on an object that doesn't exist.

[Some people love this behavior](https://github.com/aurelia/binding/issues/129).  [Other people don't like it](https://github.com/aurelia/binding/issues/204).

Maybe we can make the behavior configurable?

cc @EisenbergEffect, @danfma

### PR DESCRIPTION
**Pull request by jdanyow**
fixes #205

### CODE REVIEW

**Comment by jdanyow** [comment]
How does this look (aside from needing tests)? Can anyone think of a better name for the option?

Public API is the options property on the binding engine instance.

**Comment by EisenbergEffect** [comment]
@jdanyow Should we log something if the settings is "false" but the instance doesn't exist?

**Comment by jdanyow** [comment]
Tough call- I think some people (myself included) would think we should log when the object is automatically created as opposed to when assignment is skipped. There are developers on both sides of this issue.  Here's an example of the most common way this issue crops up: https://gist.run/?id=73ef440e9efde8b164ca

**Comment by EisenbergEffect** [comment]
I suppose we could also have a logging setting. What do you think?

**Comment by EisenbergEffect** [comment]
@jdanyow Where are we at on this also considering the binding behavior idea.

**Comment by jdanyow** [comment]
closing- this is not up to date with the current plan outlined in https://github.com/aurelia/binding/issues/205

**Pull request closed without merging**
