### PR TITLE
fix(element-observation): fix number datatype support in styling

### LINKED ISSUE #518: Element observation styling not accepting number datatype
**I'm submitting a bug report**

* **Library Version:**
1.0.6

* **Browser:**
all

* **Language:**
all

**Current behavior:**
@khenderick https://github.com/aurelia/templating-resources/issues/251#issuecomment-250991098
Numbers aren't supported in style binding.

The following code
`css.bind="{opacity: !output.inUse ? 0.65 : 1}"`

Results in the error
`TypeError: value.indexOf is not a function`

**Expected/desired behavior:**
Styling should support numbers as well as strings.
The specified opacity number should be applied to the element.

### PR DESCRIPTION
**Pull request by CasiOo**
Fixes #518

### CODE REVIEW

**Comment by jdanyow** [comment]
Thanks @CasiOo - this looks good to me- @z-brooks what do you think?

**Comment by z-brooks** [comment]
@jdanyow looks good :+1: .

**Comment by CasiOo** [comment]
@Gheoan I'm not sure I understand.
The following wouldn't be valid JavaScript
`observer.setValue({ opacity: 0.65 !important });`

Can you describe it a different way for me?

**Comment by Gheoan** [comment]
@CasiOo
`observer.setValue('opacity: 0.1 !important');` should do it.

**Comment by CasiOo** [comment]
Does the additional test cover your concerns @Gheoan ?

**Comment by Gheoan** [comment]
@CasiOo Yes.

**Pull request merged**
