### PR TITLE
Change only style properties set through observer/binding

### PR DESCRIPTION
**Pull request by z-brooks**
https://github.com/aurelia/binding/issues/290

Existing tests still pass. Tested in a skeleton as well.

### CODE REVIEW

**Comment by jdanyow** [comment]
@z-brooks :muscle: thanks! :sparkles:

**Comment by stoffeastrom** [comment]
@jdanyow Is it possible to change a property in a style object and it will update? Doesn't seem to work, should it? It's a bit tedious to update the whole style object if it's only one property that needs to change..

**Comment by jdanyow** [comment]
Agreed, that will require some more work. I wonder if this would be better:
```html
<div class.my-class.bind="foo"
     style.background-color.bind="backgroundColor">
</div>
```
Than:
```html
<div class.bind="{ 'my-class': foo }"
     style.bind="{ 'background-color': backgroundColor }">
</div>
```

thoughts?

**Comment by stoffeastrom** [comment]
Yes that seems really nice!

**Comment by EisenbergEffect** [comment]
I could go for that. Can we plug that into our parser in a simple way without affecting other things negatively?

**Comment by jdanyow** [comment]
nice! will look into it

**Pull request merged**
