### PR TITLE
fix(event-manager): Firefox shadow dom event handling

### LINKED ISSUE #765: Delegate does not support shadow dom for Firefox
**I'm submitting a bug report**

Related to: #755 

* **Library Version:**
2.5.0

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
10.15.1

* **NPM Version:**
6.10.2

* **Browser:**
Firefox 70.0.1 (64-bits)

* **Language:**
all

**Current behavior:**
Clicking nested elements in shadow dom does not trigger click delegate.

In my case this fails for a search input with a search button.
image

The search button has a click.trigger which should dispatch a custom "on-search" event. This fails due to:
```ts
// event-manager.js:7
function findOriginalEventTarget(event) {
  return (event.path && event.path[0]) || (event.deepPath && event.deepPath[0]) || event.target;
}
```

**Result in firefox:**
`spec-input-search` (custom search component containing the search button)

Chrome (which works properly):
`button`

**Reason for failure:**
Firefox does not have event.path or deepPath so falls back to target which does not take shadow dom into account. 

**Proposed solution:**
Use composedPath before using fallback to event.target

**Expected/desired behavior:**
When using shadow dom, nested should handle click delegate properly

### PR DESCRIPTION
**Pull request by michaelw85**
Return correct original event target for Firefox

Closes #765

### CODE REVIEW

**Comment by michaelw85** [comment]
@bigopon @fkleuver Followup for #755

**Comment by fkleuver** [comment]
@bigopon @michaelw85 Do we have any particular tests for this? In v2 I did this a little bit differently, starting with the more specific APIs first and falling back to the more generic ones. I seem to recall discussion that there was something wrong about v2's event handling but not sure if it applied to this.
Should this code be changed to be in sync with v2? https://github.com/aurelia/aurelia/blob/master/packages/runtime-html/src/observation/event-manager.ts#L16
Or should it be the other way around you think? @bigopon 
Either way I'd prefer if we kept v1 and v2 the same in this particular regard.

**Comment by michaelw85** [comment]
@fkleuver I tested the fix locally in my project (created a branch with updated dist). The method is private and I did not think any tests would run in Firefox so I did not write a unit test. I could of course quite easily provide a simple component that could be used to verify the fix.

On the approach, I would prefer the v2 setup. This seems correct to me, I thought the composedPath is the "new" standardized api for getting the target info. I was thinking about this approach with my change but decided to minimize impact. if @bigopon agrees I can update the PR to match v2

**Comment by bigopon** [comment]
If `path` and `composedPath` are not the same in chrome, then we cannot move `composedPath` in front of `path`, unless we have a way to configure it in the event manager

**Comment by michaelw85** [comment]
`path` should be the same, apparently this was the initial proposal by Google and this became `composedPath()`. `composedPath` is the standard now. 

A quick test in my app shows they are identical in this scenario:
image

**Comment by bigopon** [comment]
@michaelw85 thanks for checking, If so let's go with @fkleuver 's suggestion and make it behave like v2

**Comment by michaelw85** [comment]
ok will update.

@fkleuver I just spotted a mistake in the v2 code. `event.deepPath()[0]` deepPath is an array not a method.
Documentation: https://developer.mozilla.org/en-US/docs/Web/API/Event
```
Event.deepPath 
An Array of DOM Nodes through which the event has bubbled.
```

**Comment by michaelw85** [comment]
@bigopon @fkleuver Can this PR be reviewed or are you waiting for me to do any additional changes?

**Comment by fkleuver** [comment]
I think we're good. Thank you!

@EisenbergEffect Unless you see any issue, as far as I'm concerned we can merge/release this. It's now in sync with v2.

**Comment by EisenbergEffect** [comment]
Thanks everyone! We'll get this out next week.

**Pull request merged**
