### PR TITLE
fix(StyleObserver): parse style without breaking urls

### LINKED ISSUE #301: background-image broken in latest versions
Something changed in the latest version of Aurelia, breaking the `background-image` style.

```
<div style="background-image: url(http://demos.telerik.com/kendo-ui/content/web/Customers/${CustomerID}.jpg);"></div>
```

gets resolved to

image

which gives a 404 to "localhost:3000/http"

I have reproduced it here: https://github.com/JeroenVinke/background-image-bug/tree/master/src

I reverted to the previous versions and it worked with those

### PR DESCRIPTION
**Pull request by z-brooks**
Regex was splitting style strings at all : and breaking urls

Fixes #301

### CODE REVIEW

**Comment by jdanyow** [comment]
@z-brooks thanks for fixing this so quickly- would you mind adding a test for this case?

thanks!

**Comment by z-brooks** [comment]
Sure thing.

**Comment by z-brooks** [comment]
Ok, tests done.

**Comment by EisenbergEffect** [comment]
@jdanyow CLA is confirmed. Please merge if you think it's ready. Thanks!

**Comment by EisenbergEffect** [comment]
@jdanyow Is this ready to merge? I can merge it. Just let me know. I'd like to get some new releases out tomorrow, if possible.

**Comment by jdanyow** [comment]
thanks again @z-brooks

**Comment by andrevlins** [comment]
I think this problem still happening when ports are included in url like: http://host:port/image.jpg

**Comment by WorldMaker** [comment]
Also, there are URLs that don't have slashes like `blob:` URLs.

**Pull request merged**
