### PR TITLE
Reduce node_modules directory size

### PR DESCRIPTION
**Pull request by pndewit**
Apparently I am having some modules that require a different version of some aurelia modules and these reports folders are over 1MB each. There might be even more to gain in this area.

EDIT: Let me know which directories/files can also be added to this list and I will update this PR. Noticed also other Aurelia repo's can have this directory. Let me know if you need me to submit a PR there too.

### CODE REVIEW

**Comment by fkleuver** [comment]
That's.. interesting. Good find. We definitely don't want that stuff in the published outputs

**Comment by pndewit** [comment]
Bump, is anyone looking at the impact or other directories/files that can be removed from the published output?

**Comment by bigopon** [comment]
I've rarely look in to it. but the change lgtm. Pinging @EisenbergEffect

**Comment by EisenbergEffect** [comment]
Frankly, I forgot this was even in there. We haven't really used this much in a long tie. We can certainly merge this. @pndewit If you want to submit similar PRs to other repos that are causing issues, we can certainly get those merged.

**Comment by pndewit** [comment]
No problem, glad I could help. Creating PRs now.

**Comment by StrahilKazlachev** [comment]
If we are going down that road, I *strongly* support @jods4 suggestion, from some time ago, for using the [files](https://docs.npmjs.com/files/package.json#files) field in  `package.json`.

**Pull request merged**
