### PR TITLE
Coerce value to boolean

### PR DESCRIPTION
**Pull request by djedi**
Fix for https://github.com/aurelia/binding/issues/299

### CODE REVIEW

**Comment by z-brooks** [comment]
I think `Boolean([...])` is always *true*. Might be better to move that cast after the array check?

**Comment by jdanyow** [comment]
@djedi awesome!

We'd love to merge this PR but will first need you to do a couple things:

1. amend the commit message (our release notes are automated based on a simple commit message format) 
2. sign the CLA

Instructions can be found in the `contributing.md` file in any of the repos.

Much appreciated!

**Comment by jdanyow** [comment]
@z-brooks good point

@djedi please run the tests: `karma start` (instructions in readme.md)

fyi: 

result

Also, not sure if you're aware, but the value will be coerced, meaning 0 will end up becoming false on your property.  You may just want to use a value converter.

**Comment by EisenbergEffect** [comment]
@djedi We will need a CLA sig before we can move ahead with this.
@jdanyow Does this still need fixes?

**Comment by jdanyow** [comment]
@EisenbergEffect yes it does

**Comment by EisenbergEffect** [comment]
@jdanyow Where are we at on this? Recommendations?

**Comment by jdanyow** [comment]
Going to close this.  It needs work to address the issue @z-brooks mentioned, tests, etc.  I'm on the fence with the hard-coded coercion, it's caused a bunch of problems/confusion in input.value binding, need to take a step back and come up with a solution that will work across the binding system.

**Comment by z-brooks** [comment]
gave this a shot before the close. It's fine if none of this is usable

https://github.com/z-brooks/binding/blob/master/src/checked-observer.js#L59
Does preserving the number value matter? Too ugly?
https://github.com/z-brooks/binding/blob/master/src/checked-observer.js#L83
Test.
https://github.com/z-brooks/binding/blob/master/test/checked-observer.spec.js#L185

**Pull request closed without merging**
