### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by MeirionHughes**
allow typescript to find npm module typings.

### CODE REVIEW

**Comment by MeirionHughes** [comment]
this needs to be done on pretty much all the projects btw.

**Comment by EisenbergEffect** [comment]
I don't believe this will work in its present form. We need to change the format of the dts files as well. The team has been discussing this and making plans. @niieani can provide some commentary.

**Comment by niieani** [comment]
Indeed, first we need to deal with this: https://github.com/aurelia/dependency-injection/pull/95.

**Comment by MeirionHughes** [comment]
ahh yes, you've declared a module export; fair enough. Just as well I didn't go off and PR them all. :D

**Comment by EisenbergEffect** [comment]
I'm going to close this for now, but know that we are working on this and planning to use the typings strategy. We hope to get this in place pretty soon.

**Pull request closed without merging**
